server {
  listen 18080;
  server_name flight.srv1821288.hstgr.cloud;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ /index.html; }
  location ~* \.(js|css)$ { expires 1h; add_header Cache-Control "public"; }
}
